### PR TITLE
About page finished

### PR DESCRIPTION
**Pull request by jerrylee17**

### CODE REVIEW

**Comment by hsorathia** [comment]
Looks good! 
Can you make it so that if the user zooms in their page the rows produced are also centered? 
image

**Comment by jerrylee17** [comment]
> Looks good!
> Can you make it so that if the user zooms in their page the rows produced are also centered?
> image

resolved

**Comment by hsorathia** [comment]
> > Looks good!
> > Can you make it so that if the user zooms in their page the rows produced are also centered?
> > image
> 
> resolved
wait hold on

image

**Review by hsorathia — APPROVED** [review]
great job!

**Pull request merged**
